eureka:
  client:
    serviceUrl:
      # defaultZone: http://localhost:8010/eureka/
      defaultZone: http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/,http://eureka-primary:8011/eureka

---
spring:
  profiles: subject
word: I,You,He,She,It

---
spring:
  profiles: verb
word: ran,knew,had,saw,bought
---
spring:
  profiles: article
word: a,the

---
spring:
  profiles: adjective
word: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
word: boat,book,vote,seat,backpack,partition,groundhog  
