eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
      #defaultZone: http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/,http://eureka-primary:8011/eureka
  instance:
    instanceid: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

---
spring:
  profiles: subject
  application: 
    name: subject-server
word: I,You,He,She,It

---
spring:
  profiles: verb
  application:
    name: verb-server
word: ran,knew,had,saw,bought
---
spring:
  profiles: article
  application:
    name: article-server
word: a,the
---
spring:
  profiles: adjective2
  applicaiton:
    name: adj-server
word: reasonable,leaky,suspicious,ordinary,unlikely
---
spring:
  profiles: adjective
  application:
    name: arjective-server
word: reasonable,leaky,suspicious,ordinary,unlikely
---
spring:
  profiles: noun
  application:
    name: noun-server
word: boat,book,vote,seat,backpack,partition,groundhog  
---
spring:
  profiles: cold-noun
  application:
    name: noun-server
word: icicle,refrigerator,blizzard,snowball
